<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="14.1.0" />
      <PackageReference Include="NetCord" Version="1.0.0-alpha.480" />
      <PackageReference Include="NetCord.Hosting" Version="1.0.0-alpha.480" />
      <PackageReference Include="NetCord.Hosting.AspNetCore" Version="1.0.0-alpha.480" />
      <PackageReference Include="NetCord.Hosting.Services" Version="1.0.0-alpha.480" />
      <PackageReference Include="NetCord.Services" Version="1.0.0-alpha.480" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AlboV2.Features\AlboV2.Features.csproj" />
      <ProjectReference Include="..\AlboV2.Shared\AlboV2.Shared.csproj" />
    </ItemGroup>

</Project>
